### ISSUE TITLE
Twisted IRC seems not to be able to connect to ProvisionIRCd

### ISSUE THREAD

**Issue by inhahe** [Y4kuzi/ProvisionIRCd#8]
I'm writing an IRC client in Python using Twisted's irc.py, and when I connect to the ProvisionIRCd server on localhost it keeps disconnecting immediately with no message and no network error except cleanly closing port. Twisted's logging shows that irc.py raises IRCBadMessage because there's an empty message. I have no idea if that's why it's closing; I kinda doubt it. 

I'm able to connect to UnrealIRCd on localhost just fine.

Because I can just use UnrealIRCd instead, this bug is no biggy if you don't want to delve into it. Though I like the idea of having a Python IRC server in case I ever want to modify it to do special things that other IRC servers don't (assuming I can figure out the overall structure--I'm bad at doing that with large projects), and if I ever run ProvisionIRCd for others to use it would be nice if people using Twisted IRC or any other software the issue may affect could connect.

Here's what Twisted logs each time it disconnects:

2021-03-27 04:02:03-0400 [ServerConnection,client] <twisted.internet.tcp.Connector instance at 0x4b103a0 disconnected IPv4Address(type='TCP', host='localhost', port=6667)> will retry in 10 seconds
2021-03-27 04:02:03-0400 [-] Stopping factory <__main__.ServerFactory object at 0x04B100A0>
2021-03-27 04:02:14-0400 [-] Starting factory <__main__.ServerFactory object at 0x04B100A0>
2021-03-27 04:02:14-0400 [ServerConnection,client]
2021-03-27 04:02:14-0400 [ServerConnection,client] Traceback (most recent call last):
          File "D:\qttirc0.1\irc.py", line 2659, in lineReceived
            prefix, command, params = parsemsg(line)
          File "D:\qttirc0.1\irc.py", line 106, in parsemsg
            raise IRCBadMessage("Empty line.")
        irc.IRCBadMessage: Empty line.

**Comment by Y4kuzi** [comment]
I have tried a few Twisted IRC bots without any issues.
First I tried this example I found on Google: https://gist.github.com/habnabit/5823693
Then I cloned your `ircbot` repository and also managed to connect successfully.

You can try to run the IRCd in debug mode so that it shows some debug output.
You can do that by running the IRCd with the --nofork flag.
Example: python3 ircd.py --nofork

Then we can see if it yields any useful information.
